Repository geekcell/terraform-aws-iam-policy, pull requests merged in 2023-01, with the labels that each got.

#1 feat: Initial commit
  .gitattributes
  .terraform-docs.yml
  README.md
  docs/assets/logo.svg
  docs/badges.md
  examples/basic-example/main.tf
  examples/statements/main.tf
  examples/templates/main.tf
  main.tf
  outputs.tf
  templates/assume/github-repo-webidentity.tftpl
  templates/codedeploy/ecs-blue-green-deployment.tftpl
  templates/ecr/push-and-pull.tftpl
  variables.tf
  versions.tf
Labels: bump:major

#2 fix: rename template variables so they make more sense
  templates/codedeploy/ecs-blue-green-deployment.tftpl
  templates/ecr/push-and-pull.tftpl
Labels: bump:patch

#4 feat: add Templates for S3 Read & Read+Write
  templates/s3/read-write.tftpl
  templates/s3/read.tftpl
Labels: bump:minor
